Budget Planner/force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Budget Planner/force-app/main/default/objects/Budget__c/fields/Available_Budget__c.field-meta.xml
<CustomField>
    <fullName>Available_Budget__c</fullName>
    <formula>Total_Budget__c  -  Budget_Spent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget__c/fields/Budget_Spent__c.field-meta.xml
<CustomField>
    <fullName>Budget_Spent__c</fullName>
    <label>Budget Spent</label>
    <summarizedField>Budget_Category__c.Cost__c</summarizedField>
    <summaryForeignKey>Budget_Category__c.Budget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget__c/fields/Total_Budget__c.field-meta.xml
<CustomField>
    <fullName>Total_Budget__c</fullName>
    <label>Total Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget_Category__c/Budget_Category__c.object-meta.xml
<CustomObject>
    <label>Budget Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Budget Planner/force-app/main/default/objects/Budget_Category__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Budget Categories</relationshipLabel>
    <relationshipName>Budget_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget_Category__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Budget Planner/force-app/main/default/classes/BudgetCharts.cls
public class BudgetCharts {
    @AuraEnabled(cacheable=true)
    public static List<Budget__c> getBudgetCharts(Id recordId, String duration) {
        List<Budget__c> budgetData = new List<Budget__c>();
        
        if (UtilClass.checkBudgetAccess()) {
            budgetData = [SELECT Id, Name, Total_Budget__c, Budget_Spent__c, Available_Budget__c,
                (SELECT Id, Name, Cost__c FROM Budget_Categories__r)
                FROM Budget__c WHERE Id = :recordId WITH SECURITY_ENFORCED];
        }
        
        return budgetData;
    }
}