Budget Planner/force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Budget Planner/force-app/main/default/objects/Budget__c/fields/Available_Budget__c.field-meta.xml
<CustomField>
    <fullName>Available_Budget__c</fullName>
    <formula>Total_Budget__c  -  Budget_Spent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget__c/fields/Budget_Spent__c.field-meta.xml
<CustomField>
    <fullName>Budget_Spent__c</fullName>
    <label>Budget Spent</label>
    <summarizedField>Budget_Category__c.Cost__c</summarizedField>
    <summaryForeignKey>Budget_Category__c.Budget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget__c/fields/Total_Budget__c.field-meta.xml
<CustomField>
    <fullName>Total_Budget__c</fullName>
    <label>Total Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget_Category__c/Budget_Category__c.object-meta.xml
<CustomObject>
    <label>Budget Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Budget Planner/force-app/main/default/objects/Budget_Category__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Budget Categories</relationshipLabel>
    <relationshipName>Budget_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget_Category__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget_Category_Expense__c/Budget_Category_Expense__c.object-meta.xml
<CustomObject>
    <label>Budget Category Expense</label>
    <nameField>
        <displayFormat>BCE-{0000}</displayFormat>
        <label>Budget Category Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Category Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Budget Planner/force-app/main/default/objects/Budget_Category_Expense__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget</label>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Budget Category Expenses</relationshipLabel>
    <relationshipName>Budget_Category_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget_Category_Expense__c/fields/Budget_Category__c.field-meta.xml
<CustomField>
    <fullName>Budget_Category__c</fullName>
    <label>Budget Category</label>
    <referenceTo>Budget_Category__c</referenceTo>
    <relationshipLabel>Budget Category Expenses</relationshipLabel>
    <relationshipName>Budget_Category_Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Budget Planner/force-app/main/default/objects/Budget_Category_Expense__c/fields/Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Resource_Name__c</fullName>
    <label>Resource Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Budget Planner/force-app/main/default/classes/UtilClass.cls
public with sharing class UtilClass {
    /**
     * @description checkBudgetAccess
     * @return boolean
     */
    public static Boolean checkBudgetAccess() {
        if(
            Budget__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isAccessible() &&
            Schema.SObjectType.Budget__c.fields.Id.isAccessible() &&
            Schema.SObjectType.Budget__c.fields.Name.isAccessible() &&
            Schema.SObjectType.Budget__c.fields.Total_Budget__c.isAccessible() &&
            Schema.SObjectType.Budget__c.fields.Budget_Spent__c.isAccessible() &&
            Schema.SObjectType.Budget__c.fields.Available_Budget__c.isAccessible() &&
            Schema.SObjectType.Budget_Category__c.fields.Id.isAccessible() &&
            Schema.SObjectType.Budget_Category__c.fields.Name.isAccessible() &&
            Schema.SobjectType.Budget_Category__c.fields.Cost__c.isAccessible() &&
            Schema.SObjectType.Budget_Category__c.fields.Budget__c.isAccessible() &&
            Schema.SobjectType.Budget_Category_Expense__c.fields.Id.isAccessible() &&
            Schema.SObjectType.Budget_Category_Expense__c.fields.Name.isAccessible() &&
            Schema.SobjectType.Budget_Category_Expense__c.fields.Resource_Name__c.isAccessible() &&
            Schema.SobjectType.Budget_Category_Expense__c.fields.Cost__c.isAccessible() &&
            Schema.SobjectType.Budget_Category_Expense__c.fields.Budget__c.isAccessible() &&
            Schema.SobjectType.Budget_Category_Expense__c.fields.Budget_category__c.isAccessible()
        ){
            return true;
        }
        return false;
    }
   
}